### ISSUE TITLE
onsneak will tp to the dragon??

### ISSUE THREAD

**Issue by downboy** [DiscowZombie/Rush4TheDragon#2]
hee i try to help you find bugs and stuff, but i found this part of code that tp you to the end. Can you please add a option to disable it??

```
@EventHandler
	public void onSneak(PlayerToggleSneakEvent e){
		Player p = e.getPlayer();
		if(Rush4TheDragon.status == false){
			for(World w : Bukkit.getWorlds()){
				if(w.getName().contains("end")){
					p.teleport(new Location(Bukkit.getWorld(w.getName()), p.getLocation().getBlockX(), p.getLocation().getBlockY(), p.getLocation().getBlockZ()));
				}
			}
		}
	}
```

its in DragonDeath.java

**Comment by DiscowZombie** [comment]
Ho sorry :O it's a debeug x')

**Comment by DiscowZombie** [comment]
Thank, fixed in v2.0.2.

Is your previus issues fixed ?

**Comment by downboy** [comment]
yes it is made some small changes to your code to make sure everything is working, do you want the new code??

**Comment by DiscowZombie** [comment]
Yes, I post-it on github to allow user to contributed to code! You can make a pull request ;)
